# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layerpropertiesbase.ui'
#
# Created: Tue Apr 27 16:20:11 2010
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore
from PyQt4 import QtGui
from qrc_resources import *

class Ui_LayerPropertiesBase(object):
    def setupUi(self, LayerPropertiesBase):
        LayerPropertiesBase.setObjectName("LayerPropertiesBase")
        LayerPropertiesBase.resize(668, 426)
        icon = QtGui.QIcon(":icon.png")
        LayerPropertiesBase.setWindowIcon(icon)
        LayerPropertiesBase.setModal(True)
        self.gridLayout = QtGui.QGridLayout(LayerPropertiesBase)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtGui.QListWidget(LayerPropertiesBase)
        self.listWidget.setMinimumSize(QtCore.QSize(110, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(110, 16777215))
        self.listWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setIconSize(QtCore.QSize(64, 64))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget.setFlow(QtGui.QListView.TopToBottom)
        self.listWidget.setProperty("isWrapping", QtCore.QVariant(False))
        self.listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget.setSpacing(9)
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/symbology.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/labels.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/attributes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/general.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/metadata.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/action.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon6)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(LayerPropertiesBase)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.legendtypelabel = QtGui.QLabel(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendtypelabel.sizePolicy().hasHeightForWidth())
        self.legendtypelabel.setSizePolicy(sizePolicy)
        self.legendtypelabel.setMaximumSize(QtCore.QSize(32767, 22))
        self.legendtypelabel.setObjectName("legendtypelabel")
        self.gridLayout_4.addWidget(self.legendtypelabel, 0, 0, 1, 1)
        self.legendtypecombobox = QtGui.QComboBox(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendtypecombobox.sizePolicy().hasHeightForWidth())
        self.legendtypecombobox.setSizePolicy(sizePolicy)
        self.legendtypecombobox.setMinimumSize(QtCore.QSize(0, 26))
        self.legendtypecombobox.setMaximumSize(QtCore.QSize(32767, 22))
        self.legendtypecombobox.setObjectName("legendtypecombobox")
        self.gridLayout_4.addWidget(self.legendtypecombobox, 0, 1, 1, 1)
        self.lblTransparencyPercent = QtGui.QLabel(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTransparencyPercent.sizePolicy().hasHeightForWidth())
        self.lblTransparencyPercent.setSizePolicy(sizePolicy)
        self.lblTransparencyPercent.setObjectName("lblTransparencyPercent")
        self.gridLayout_4.addWidget(self.lblTransparencyPercent, 0, 2, 1, 1)
        self.sliderTransparency = QtGui.QSlider(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderTransparency.sizePolicy().hasHeightForWidth())
        self.sliderTransparency.setSizePolicy(sizePolicy)
        self.sliderTransparency.setMaximum(255)
        self.sliderTransparency.setProperty("value", QtCore.QVariant(0))
        self.sliderTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTransparency.setObjectName("sliderTransparency")
        self.gridLayout_4.addWidget(self.sliderTransparency, 0, 3, 1, 1)
        self.widgetStackRenderers = QtGui.QStackedWidget(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetStackRenderers.sizePolicy().hasHeightForWidth())
        self.widgetStackRenderers.setSizePolicy(sizePolicy)
        self.widgetStackRenderers.setFrameShape(QtGui.QFrame.NoFrame)
        self.widgetStackRenderers.setFrameShadow(QtGui.QFrame.Sunken)
        self.widgetStackRenderers.setObjectName("widgetStackRenderers")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.widgetStackRenderers.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.widgetStackRenderers.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.widgetStackRenderers, 1, 0, 1, 5)
        self.btnUseNewSymbology = QtGui.QPushButton(self.page_3)
        self.btnUseNewSymbology.setObjectName("btnUseNewSymbology")
        self.gridLayout_4.addWidget(self.btnUseNewSymbology, 0, 4, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelCheckBox = QtGui.QCheckBox(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCheckBox.sizePolicy().hasHeightForWidth())
        self.labelCheckBox.setSizePolicy(sizePolicy)
        self.labelCheckBox.setObjectName("labelCheckBox")
        self.gridLayout_5.addWidget(self.labelCheckBox, 0, 0, 1, 1)
        self.labelOptionsFrame = QtGui.QFrame(self.page_4)
        self.labelOptionsFrame.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOptionsFrame.sizePolicy().hasHeightForWidth())
        self.labelOptionsFrame.setSizePolicy(sizePolicy)
        self.labelOptionsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelOptionsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.labelOptionsFrame.setObjectName("labelOptionsFrame")
        self.gridLayout_5.addWidget(self.labelOptionsFrame, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mAddAttributeButton = QtGui.QToolButton(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAddAttributeButton.sizePolicy().hasHeightForWidth())
        self.mAddAttributeButton.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":mActionNewAttribute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAddAttributeButton.setIcon(icon7)
        self.mAddAttributeButton.setObjectName("mAddAttributeButton")
        self.gridLayout_6.addWidget(self.mAddAttributeButton, 0, 0, 1, 1)
        self.mDeleteAttributeButton = QtGui.QToolButton(self.page_5)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":mActionDeleteAttribute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mDeleteAttributeButton.setIcon(icon8)
        self.mDeleteAttributeButton.setObjectName("mDeleteAttributeButton")
        self.gridLayout_6.addWidget(self.mDeleteAttributeButton, 0, 1, 1, 1)
        self.mToggleEditingButton = QtGui.QToolButton(self.page_5)
        self.mToggleEditingButton.setCheckable(True)
        self.mToggleEditingButton.setObjectName("mToggleEditingButton")
        self.gridLayout_6.addWidget(self.mToggleEditingButton, 0, 2, 1, 1)
        self.mCalculateFieldButton = QtGui.QToolButton(self.page_5)
        self.mCalculateFieldButton.setCheckable(False)
        self.mCalculateFieldButton.setObjectName("mCalculateFieldButton")
        self.gridLayout_6.addWidget(self.mCalculateFieldButton, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(658, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 4, 1, 1)
        self.tblAttributes = QtGui.QTableWidget(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblAttributes.sizePolicy().hasHeightForWidth())
        self.tblAttributes.setSizePolicy(sizePolicy)
        self.tblAttributes.setMinimumSize(QtCore.QSize(256, 0))
        self.tblAttributes.setObjectName("tblAttributes")
        self.tblAttributes.setColumnCount(0)
        self.tblAttributes.setRowCount(0)
        self.gridLayout_6.addWidget(self.tblAttributes, 1, 0, 1, 5)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_7.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtGui.QScrollArea(self.page_6)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 331, 352))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.indexGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.indexGroupBox.setObjectName("indexGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.indexGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel3 = QtGui.QLabel(self.indexGroupBox)
        self.textLabel3.setObjectName("textLabel3")
        self.gridLayout_2.addWidget(self.textLabel3, 0, 0, 1, 1)
        self.txtDisplayName = QtGui.QLineEdit(self.indexGroupBox)
        self.txtDisplayName.setObjectName("txtDisplayName")
        self.gridLayout_2.addWidget(self.txtDisplayName, 0, 1, 1, 1)
        self.textLabel2 = QtGui.QLabel(self.indexGroupBox)
        self.textLabel2.setObjectName("textLabel2")
        self.gridLayout_2.addWidget(self.textLabel2, 0, 2, 1, 1)
        self.displayFieldComboBox = QtGui.QComboBox(self.indexGroupBox)
        self.displayFieldComboBox.setObjectName("displayFieldComboBox")
        self.gridLayout_2.addWidget(self.displayFieldComboBox, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.indexGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leEditForm = QtGui.QLineEdit(self.indexGroupBox)
        self.leEditForm.setObjectName("leEditForm")
        self.horizontalLayout_2.addWidget(self.leEditForm)
        self.pbnSelectEditForm = QtGui.QToolButton(self.indexGroupBox)
        self.pbnSelectEditForm.setObjectName("pbnSelectEditForm")
        self.horizontalLayout_2.addWidget(self.pbnSelectEditForm)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 2)
        self.pbnIndex = QtGui.QPushButton(self.indexGroupBox)
        self.pbnIndex.setObjectName("pbnIndex")
        self.gridLayout_2.addWidget(self.pbnIndex, 1, 3, 1, 1)
        self.leSpatialRefSys = QtGui.QLineEdit(self.indexGroupBox)
        self.leSpatialRefSys.setReadOnly(True)
        self.leSpatialRefSys.setObjectName("leSpatialRefSys")
        self.gridLayout_2.addWidget(self.leSpatialRefSys, 3, 0, 1, 4)
        self.leEditFormInit = QtGui.QLineEdit(self.indexGroupBox)
        self.leEditFormInit.setObjectName("leEditFormInit")
        self.gridLayout_2.addWidget(self.leEditFormInit, 2, 1, 1, 2)
        self.pbnChangeSpatialRefSys = QtGui.QPushButton(self.indexGroupBox)
        self.pbnChangeSpatialRefSys.setObjectName("pbnChangeSpatialRefSys")
        self.gridLayout_2.addWidget(self.pbnChangeSpatialRefSys, 2, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.indexGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.indexGroupBox, 0, 0, 1, 1)
        self.chkUseScaleDependentRendering = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.chkUseScaleDependentRendering.setCheckable(True)
        self.chkUseScaleDependentRendering.setObjectName("chkUseScaleDependentRendering")
        self.gridlayout = QtGui.QGridLayout(self.chkUseScaleDependentRendering)
        self.gridlayout.setMargin(11)
        self.gridlayout.setObjectName("gridlayout")
        self.textLabel1_2_2 = QtGui.QLabel(self.chkUseScaleDependentRendering)
        self.textLabel1_2_2.setObjectName("textLabel1_2_2")
        self.gridlayout.addWidget(self.textLabel1_2_2, 0, 2, 1, 1)
        self.textLabel1 = QtGui.QLabel(self.chkUseScaleDependentRendering)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.spinMinimumScale = QtGui.QSpinBox(self.chkUseScaleDependentRendering)
        self.spinMinimumScale.setMinimum(1)
        self.spinMinimumScale.setMaximum(100000000)
        self.spinMinimumScale.setObjectName("spinMinimumScale")
        self.gridlayout.addWidget(self.spinMinimumScale, 0, 1, 1, 1)
        self.spinMaximumScale = QtGui.QSpinBox(self.chkUseScaleDependentRendering)
        self.spinMaximumScale.setMinimum(1)
        self.spinMaximumScale.setMaximum(100000000)
        self.spinMaximumScale.setObjectName("spinMaximumScale")
        self.gridlayout.addWidget(self.spinMaximumScale, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.chkUseScaleDependentRendering, 1, 0, 1, 1)
        self.grpSubset = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grpSubset.setObjectName("grpSubset")
        self.gridlayout1 = QtGui.QGridLayout(self.grpSubset)
        self.gridlayout1.setMargin(11)
        self.gridlayout1.setObjectName("gridlayout1")
        self.txtSubsetSQL = QtGui.QTextEdit(self.grpSubset)
        self.txtSubsetSQL.setEnabled(False)
        self.txtSubsetSQL.setAcceptDrops(False)
        self.txtSubsetSQL.setAcceptRichText(False)
        self.txtSubsetSQL.setObjectName("txtSubsetSQL")
        self.gridlayout1.addWidget(self.txtSubsetSQL, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(480, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem1, 1, 0, 1, 1)
        self.pbnQueryBuilder = QtGui.QPushButton(self.grpSubset)
        self.pbnQueryBuilder.setObjectName("pbnQueryBuilder")
        self.gridlayout1.addWidget(self.pbnQueryBuilder, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.grpSubset, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_8 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.teMetadata = QtGui.QTextEdit(self.page_7)
        self.teMetadata.setLineWidth(2)
        self.teMetadata.setReadOnly(True)
        self.teMetadata.setObjectName("teMetadata")
        self.gridLayout_8.addWidget(self.teMetadata, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_9 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.actionOptionsFrame = QtGui.QFrame(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionOptionsFrame.sizePolicy().hasHeightForWidth())
        self.actionOptionsFrame.setSizePolicy(sizePolicy)
        self.actionOptionsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.actionOptionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.actionOptionsFrame.setObjectName("actionOptionsFrame")
        self.gridLayout_9.addWidget(self.actionOptionsFrame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbnLoadDefaultStyle = QtGui.QPushButton(LayerPropertiesBase)
        self.pbnLoadDefaultStyle.setObjectName("pbnLoadDefaultStyle")
        self.horizontalLayout.addWidget(self.pbnLoadDefaultStyle)
        self.pbnSaveDefaultStyle = QtGui.QPushButton(LayerPropertiesBase)
        self.pbnSaveDefaultStyle.setObjectName("pbnSaveDefaultStyle")
        self.horizontalLayout.addWidget(self.pbnSaveDefaultStyle)
        self.pbnLoadStyle = QtGui.QPushButton(LayerPropertiesBase)
        self.pbnLoadStyle.setObjectName("pbnLoadStyle")
        self.horizontalLayout.addWidget(self.pbnLoadStyle)
        self.pbnSaveStyleAs = QtGui.QPushButton(LayerPropertiesBase)
        self.pbnSaveStyleAs.setObjectName("pbnSaveStyleAs")
        self.horizontalLayout.addWidget(self.pbnSaveStyleAs)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(LayerPropertiesBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.legendtypelabel.setBuddy(self.legendtypecombobox)
        self.lblTransparencyPercent.setBuddy(self.sliderTransparency)
        self.textLabel3.setBuddy(self.txtDisplayName)
        self.textLabel2.setBuddy(self.displayFieldComboBox)
        self.textLabel1_2_2.setBuddy(self.spinMaximumScale)
        self.textLabel1.setBuddy(self.spinMinimumScale)

        self.retranslateUi(LayerPropertiesBase)
        self.stackedWidget.setCurrentIndex(0)
        self.widgetStackRenderers.setCurrentIndex(0)
        QtCore.QObject.connect(self.labelCheckBox, QtCore.SIGNAL("clicked(bool)"), self.labelOptionsFrame.setEnabled)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentRowChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(LayerPropertiesBase)
        LayerPropertiesBase.setTabOrder(self.txtDisplayName, self.displayFieldComboBox)
        LayerPropertiesBase.setTabOrder(self.displayFieldComboBox, self.leSpatialRefSys)
        LayerPropertiesBase.setTabOrder(self.leSpatialRefSys, self.pbnIndex)
        LayerPropertiesBase.setTabOrder(self.pbnIndex, self.spinMinimumScale)
        LayerPropertiesBase.setTabOrder(self.spinMinimumScale, self.spinMaximumScale)
        LayerPropertiesBase.setTabOrder(self.spinMaximumScale, self.txtSubsetSQL)
        LayerPropertiesBase.setTabOrder(self.txtSubsetSQL, self.pbnQueryBuilder)
        LayerPropertiesBase.setTabOrder(self.pbnQueryBuilder, self.buttonBox)

    def retranslateUi(self, LayerPropertiesBase):
        LayerPropertiesBase.setWindowTitle(QtGui.QApplication.translate("LayerPropertiesBase", "Layer Properties", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("LayerPropertiesBase", "Symbology", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("LayerPropertiesBase", "Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(2).setText(QtGui.QApplication.translate("LayerPropertiesBase", "Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("LayerPropertiesBase", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(4).setText(QtGui.QApplication.translate("LayerPropertiesBase", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(5).setText(QtGui.QApplication.translate("LayerPropertiesBase", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.legendtypelabel.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Legend type", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTransparencyPercent.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Transparency", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUseNewSymbology.setText(QtGui.QApplication.translate("LayerPropertiesBase", "New symbology", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCheckBox.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Display labels", None, QtGui.QApplication.UnicodeUTF8))
        self.mAddAttributeButton.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "New column", None, QtGui.QApplication.UnicodeUTF8))
        self.mAddAttributeButton.setShortcut(QtGui.QApplication.translate("LayerPropertiesBase", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.mDeleteAttributeButton.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Delete column", None, QtGui.QApplication.UnicodeUTF8))
        self.mDeleteAttributeButton.setShortcut(QtGui.QApplication.translate("LayerPropertiesBase", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.mToggleEditingButton.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Toggle editing mode", None, QtGui.QApplication.UnicodeUTF8))
        self.mToggleEditingButton.setWhatsThis(QtGui.QApplication.translate("LayerPropertiesBase", "Click to toggle table editing", None, QtGui.QApplication.UnicodeUTF8))
        self.mCalculateFieldButton.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Field calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.mCalculateFieldButton.setWhatsThis(QtGui.QApplication.translate("LayerPropertiesBase", "Click to toggle table editing", None, QtGui.QApplication.UnicodeUTF8))
        self.tblAttributes.setSortingEnabled(False)
        self.indexGroupBox.setTitle(QtGui.QApplication.translate("LayerPropertiesBase", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Display name", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Display field for the Identify Results dialog box", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setWhatsThis(QtGui.QApplication.translate("LayerPropertiesBase", "This sets the display field for the Identify Results dialog box", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Display field", None, QtGui.QApplication.UnicodeUTF8))
        self.displayFieldComboBox.setWhatsThis(QtGui.QApplication.translate("LayerPropertiesBase", "Use this control to set which field is placed at the top level of the Identify Results dialog box.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Edit UI", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectEditForm.setText(QtGui.QApplication.translate("LayerPropertiesBase", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnIndex.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Create Spatial Index", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnChangeSpatialRefSys.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Specify the coordinate reference system of the layer\'s geometry.", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnChangeSpatialRefSys.setWhatsThis(QtGui.QApplication.translate("LayerPropertiesBase", "Specify the coordinate reference system of the layer\'s geometry.", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnChangeSpatialRefSys.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Specify CRS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Init function", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUseScaleDependentRendering.setTitle(QtGui.QApplication.translate("LayerPropertiesBase", "Use scale dependent rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2_2.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMinimumScale.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Minimum scale at which this layer will be displayed. ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMaximumScale.setToolTip(QtGui.QApplication.translate("LayerPropertiesBase", "Maximum scale at which this layer will be displayed. ", None, QtGui.QApplication.UnicodeUTF8))
        self.grpSubset.setTitle(QtGui.QApplication.translate("LayerPropertiesBase", "Subset", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnQueryBuilder.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Query Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnLoadDefaultStyle.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Restore Default Style", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSaveDefaultStyle.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Save As Default", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnLoadStyle.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Load Style ...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSaveStyleAs.setText(QtGui.QApplication.translate("LayerPropertiesBase", "Save Style ...", None, QtGui.QApplication.UnicodeUTF8))

